version: "3"

dotenv:
  - ".env"

tasks:
  default:
    cmds:
      - go run cmd/main.go
    silent: true
  setup:
    cmds:
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - go install github.com/cosmtrek/air@latest
  dev:
    cmds:
      - air
  build:
    cmds:
      - go build cmd/main.go
  mg-up:
    cmds:
      - migrate -database ${POSTGRES_URL} -path postgres/migrations up
  mg-force:
    cmds:
      - migrate -database ${POSTGRES_URL} -path postgres/migrations force 1
  mg-down:
    cmds:
      - migrate -database ${POSTGRES_URL} -path postgres/migrations down -all
  mg-drop:
    cmds:
      - migrate -database ${POSTGRES_URL} -path postgres/migrations drop -f
  mg-create:
    cmds:
      - migrate create -ext sql -dir postgres/migrations -seq {{.CLI_ARGS}}
