# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - go run cmd/main.go
    silent: true

  setup:
    cmds:
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - go install github.com/cosmtrek/air@latest

  dev:
    cmds:
      - air

  build:
    cmds:
      - go build cmd/main.go
