DROP TABLE IF EXISTS "Form";

DROP TABLE IF EXISTS "Contact";

DROP TABLE IF EXISTS "Admin";

DROP TABLE IF EXISTS "Route";

DROP TABLE IF EXISTS "DestinationRoute";

DROP TABLE IF EXISTS "Route";

DROP TABLE IF EXISTS "Destination";

DROP TABLE IF EXISTS "User";

DROP TABLE IF EXISTS "Credential";

DROP TYPE IF EXISTS "FormType";

DROP TYPE IF EXISTS "Gender";

DROP TYPE IF EXISTS "Role";

DROP TYPE IF EXISTS "CredentialType";

DROP TYPE IF EXISTS "FormStatus";