ALTER TABLE IF EXISTS "Form"
DROP CONSTRAINT "FkFormDestinationRoute";

ALTER TABLE IF EXISTS "Form"
DROP CONSTRAINT "FkFormAdminScanner";

ALTER TABLE IF EXISTS "Form"
DROP CONSTRAINT "FkFormAdminValidator";

ALTER TABLE IF EXISTS "Form"
DROP CONSTRAINT "FkFormContact";

ALTER TABLE IF EXISTS "DestinationRoute"
DROP CONSTRAINT "FkRoute";

ALTER TABLE IF EXISTS "DestinationRoute"
DROP CONSTRAINT "FkDestination";


ALTER TABLE IF EXISTS "User"
DROP CONSTRAINT "FkUserForm";

ALTER TABLE IF EXISTS "User"
DROP CONSTRAINT "FkUserCredential";

