ALTER TABLE IF EXISTS "Form"
DROP CONSTRAINT IF EXISTS "FkFormDestinationRoute";

ALTER TABLE IF EXISTS "Form"
DROP CONSTRAINT IF EXISTS "FkFormAdminScanner";

ALTER TABLE IF EXISTS "Form"
DROP CONSTRAINT IF EXISTS "FkFormAdminValidator";

ALTER TABLE IF EXISTS "Form"
DROP CONSTRAINT IF EXISTS "FkFormContact";

ALTER TABLE IF EXISTS "DestinationRoute"
DROP CONSTRAINT IF EXISTS "FkRoute";

ALTER TABLE IF EXISTS "DestinationRoute"
DROP CONSTRAINT IF EXISTS "FkDestination";

ALTER TABLE IF EXISTS "User"
DROP CONSTRAINT IF EXISTS "FkUserForm";

ALTER TABLE IF EXISTS "User"
DROP CONSTRAINT IF EXISTS "FkUserCredential";

